apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql
  template:
    metadata
      name: 
    label:
      name: wordpress
    spec:
      containers:
      image: wordpress
      container: wordpress
      
